[package]
name = "lancelot-bin"
version = "0.8.0"
description = "binary analysis tools for x32/x64 PE files"
authors = ["William Ballenthin <william.ballenthin@fireeye.com>"]
license = "Apache-2.0"
edition = "2021"
homepage = "https://github.com/williballenthin/lancelot"
repository = "https://github.com/williballenthin/lancelot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
clap = "3"
ansi_term = "0.12"
hexyl = "0.12"
fern = "0.6"
chrono = "0.4"
anyhow = "1"
thiserror = "1"
better-panic = "0.3"
goblin = "0.6"
ar = "0.9"
hex = "0.4"
serde_json = "1.0"

lancelot = { path = "../core", version = "0.8.0" }
lancelot-flirt = { path = "../flirt", version = "0.8.0" }
