[package]
name = "pylancelot"
version = "0.7.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2021"
homepage = "https://github.com/williballenthin/lancelot"
repository = "https://github.com/williballenthin/lancelot"

[lib]
name = "lancelot"
crate-type = ["cdylib"]

[dependencies]
lancelot = { path = "../core", version = "0.7.0" }
pyo3 = { version = "0.15"}
anyhow = "1"
zydis = { git = "https://github.com/williballenthin/zydis-rs", branch = "fix-26" }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[package.metadata.maturin]
requires-dist = ["pefile"]
classifier = [
  "Programming Language :: Rust",
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Topic :: Security",
  "Topic :: Software Development :: Disassemblers",
]
